[versions]
java = "17"
kotlin = "2.1.10"
kotest = "5.9.1"
ignition = "8.3.8"
modl = "0.5.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
modl = { id = "io.ia.sdk.modl", version.ref = "modl" }

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

ignition-common = { group = "com.inductiveautomation.ignitionsdk", name = "ignition-common", version.ref = "ignition" }
ignition-gateway-api = { group = "com.inductiveautomation.ignitionsdk", name = "gateway-api", version.ref = "ignition" }
ignition-designer-api = { group = "com.inductiveautomation.ignitionsdk", name = "designer-api", version.ref = "ignition" }
ignition-client-api = { group = "com.inductiveautomation.ignitionsdk", name = "client-api", version.ref = "ignition" }

kotest-junit = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }

[bundles]
common = ["ignition-common"]
gateway = ["ignition-common", "ignition-gateway-api"]
designer = ["ignition-common", "ignition-designer-api", "ignition-client-api"]
kotest = ["kotest-junit", "kotest-assertions-core"]
