/**
 * The shape of `src/data/tools.json`, which is generated by
 * `./gradlew :tools:tool-docs:generateToolDocs`.
 *
 * The per-tool object is `Tool.toJson()` from the module itself — the same method the MCP server
 * uses on the wire — so this interface also describes exactly what a client receives from
 * `tools/list`. Keeping it typed means a change to the generator's output fails `npm run typecheck`
 * rather than rendering an empty table.
 */

export interface JsonSchemaProperty {
  type?: string;
  description?: string;
  default?: unknown;
  enum?: string[];
  items?: {type?: string};
}

export interface ToolInputSchema {
  type: string;
  properties: Record<string, JsonSchemaProperty>;
  required: string[];
  additionalProperties: boolean;
}

export interface ToolAnnotations {
  title: string;
  readOnlyHint: boolean;
  destructiveHint: boolean;
}

export interface ToolDoc {
  name: string;
  title: string;
  description: string;
  inputSchema: ToolInputSchema;
  annotations: ToolAnnotations;
}

export interface ToolGroup {
  id: string;
  label: string;
  tools: ToolDoc[];
}

export interface ToolScope {
  id: string;
  label: string;
  endpoint: string;
  groups: ToolGroup[];
}

export interface ToolsDocument {
  schemaVersion: number;
  ignitionVersion: string;
  scopes: ToolScope[];
}
